### ISSUE TITLE
Spurious "end" inserted after format.html

### ISSUE THREAD

**Issue by jlnr** [kaiwood/vscode-endwise#10]
Big thanks for this useful extension 👍

There's one corner case where I see an extra `end` every time:

![respond_to](https://user-images.githubusercontent.com/70772/42078008-2e45de9a-7b7b-11e8-8e0e-64feef292605.gif)

It seems to be triggered by the word "format", but I'm not sure why.

**Comment by kaiwood** [comment]
Thanks for the report!

My bad, the regex I used didn't check for spaces after keywords, so `format.html` was basically the same as `for i in [1, 2]`. Fixed in v1.2.4.

**Comment by jlnr** [comment]
Works like a charm! Thanks.
