### ISSUE TITLE
Moves the cursor a space to the right when moving a dot call to a new line

### ISSUE THREAD

**Issue by grahamotte** [kaiwood/vscode-endwise#11]
Getting this behavior on v1.2.4 with only endwise installed.

![2018-07-20 14 13 15](https://user-images.githubusercontent.com/6063967/43025571-23ee7486-8c27-11e8-84c4-9e84b12cbd6d.gif)

**Comment by kaiwood** [comment]
Good catch, thanks for reporting.

Should be fixed now (v1.3.2)
