### ISSUE TITLE
Inserts "end" when already inside valid block

### ISSUE THREAD

**Issue by atombender** [kaiwood/vscode-endwise#2]
Example:

![endwise2](https://cloud.githubusercontent.com/assets/50314/26473524/e3c01cf0-4179-11e7-9a4d-2b49b98d431d.gif)

The method already has an `end`. The extension should only insert an `end` when the AST is unbalanced.

**Comment by kaiwood** [comment]
Solved via 9b7f5a4df08cedf39bed1b25162894310cbd55cf

**Comment by atombender** [comment]
👍
