### ISSUE TITLE
Extra "end" is getting added for single line definitions

### ISSUE THREAD

**Issue by jittrfunc** [kaiwood/vscode-endwise#4]
Hi, using this extension I am getting an extra "end" added for single line definitions.

Example:
def test; "do something"; end  (Here another "end" is getting added after pressing enter)

I have created a PR #3  to fix the same. You can review the changes and also pull it in if satisfactory.

**Comment by kaiwood** [comment]
#3 is merged, fixed release for the market place is on its way. Thanks again 👍
