### ISSUE TITLE
Disables suggestion autocomplete on enter

### ISSUE THREAD

**Issue by keithmattix** [kaiwood/vscode-endwise#5]
As of version 1.14.1, I can no longer persist my suggestions with the enter key; I have to press the tab key. Hitting enter simply results in a newline without the suggestion applied.

Platform: macOS Sierra
VS Code version: 1.14.1

**Comment by kaiwood** [comment]
Good catch, I have this disabled in my settings so didn't even notice. Thanks!

Fixed via ebd84238c548b66e10e92da6ed923066f6edb34e 
Update is available in the Marketplace.
