### ISSUE TITLE
Problem with vim extension when using "/" search

### ISSUE THREAD

**Issue by nolanpro** [kaiwood/vscode-endwise#6]
First thank you for this great extension! I ran into an issue when searching with "/" in vim Normal Mode. After typing the search query and hitting enter, vim's expected behavior is to go to the first found match. However, when hitting enter in vim's "search in progress" mode, endwise adds a new line instead.

Endwise seems to be conflicting with vim's enter keybinding. When disabling endwise, the vim extension behaves as expected. Thanks!

**Comment by kaiwood** [comment]
Thanks for bringing this to my attention! 👍 

I don't use the vim extension myself, so I didn't notice. Search mode is fixed with the update from a couple of minutes ago. Couldn't find any other mode that might be blocked on a quick glimpse, but if you find anything else feel free to report it.

**Comment by nolanpro** [comment]
Works great, thanks!
