### ISSUE TITLE
Lag when entering newline

### ISSUE THREAD

**Issue by C-Flatla** [kaiwood/vscode-endwise#7]
This extension has been working great for months, but now I am seeing large amounts of lag when entering new lines. When I disable this extension the lag goes away entirely.

![endwise-lag](https://user-images.githubusercontent.com/5545625/35596918-3747c9c6-05d9-11e8-90ce-f5609ee64f1c.gif)

OS: macOS Sierra 10.12.5
VSCode Version: 1.19.3

Any help would be greatly appreciated.

**Comment by kaiwood** [comment]
Hmm... I noticed the slowdowns too, but thought there is something wrong with my ageing computer. The strange thing is, that there was no new release of VSCode in between, so nothing changed in the API endpoints… 

I'll investigate, please stay tuned ;)

**Comment by C-Flatla** [comment]
So there might not be an issue with this extension.

Disabling the [VS-Ruby extension](https://marketplace.visualstudio.com/items?itemName=rebornix.Ruby) seems to fix this issue. Might be because of this issue: https://github.com/rubyide/vscode-ruby/issues/251.

**Comment by kaiwood** [comment]
Tracked it down, everytime enter is pressed, a Rubocop process for linting spawns and the whole document view blocks while its running. Its basically the issue reported here: https://github.com/rubyide/vscode-ruby/issues/252

Installing the older version seems to help as a temporary workaround (there is a direct link to the older version inside the thread). I'm still trying to find a proper solution though.

**Comment by kaiwood** [comment]
Ok, just tested it with the latest Ruby extension 0.18.0 (which added a debouncer for the linters) and everything seems to work fast again. Closing this.
